// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{}}
];
